In [1]:
import pickle
import sys
sys.path.append("/nfs/team/nlp/users/rgupta/NMT/code/GNN-Semantic-Similarity")
from gnn.models.bilstm import BILSTM
import numpy as np
import torch
import glob

In [26]:
bilstm_fs = glob.glob(f"../logs/ranking_bilstm*")
gcn_fs = glob.glob(f"../logs/ranking_gcn*")

In [27]:
def get_mrr(f_names):
    mrrs = []
    for f_name in f_names:
        
        with open(f_name) as f:
            for line in f:
                if "mrr" in line:
                    line = line.strip()
                    #print(line)
                    mrr = line.split("mrr:")[-1].strip()
                    mrrs.append(float(mrr))
                    #break
    return mrrs

In [28]:
bilstm = np.array(get_mrr(bilstm_fs))
gcn = np.array(get_mrr(gcn_fs))

In [29]:
np.max(bilstm)

0.6665

In [30]:
np.max(gcn)

0.4405

In [3]:
t1 = torch.randn(3,4,5)
t2 = torch.randn(3,4,5)

In [7]:
torch.cat((t1, t2), dim=-1).shape

torch.Size([3, 4, 10])

In [40]:
l = torch.tensor([0,2,1])

In [45]:
t

tensor([[[-0.3349, -2.3859,  0.9394, -0.5300, -0.0873],
         [ 1.1515,  1.3651,  1.2636,  0.3900,  0.2895],
         [ 1.5420,  0.1927,  0.4795, -0.5437, -0.8179],
         [-2.3833, -0.0490,  0.2781, -0.5772, -0.9853]],

        [[-0.7101, -0.6641, -0.5311,  0.0880,  0.2135],
         [-1.0279,  0.7321,  1.9088,  0.9577,  2.7588],
         [ 0.4350,  1.0682,  1.0461, -0.0229, -0.0103],
         [ 0.5641,  0.2650, -2.1782, -0.2950, -0.1581]],

        [[ 0.8426,  1.2692, -0.6953, -1.3845,  0.4879],
         [ 0.1144,  2.2331, -0.1329, -1.0320,  1.0635],
         [-1.9905, -1.8087, -1.2040,  0.0284,  0.5279],
         [ 1.1005, -1.9029, -0.0916, -2.5649, -1.6604]]])

In [44]:
t[torch.arange(3),l,:]

tensor([[-0.3349, -2.3859,  0.9394, -0.5300, -0.0873],
        [ 0.4350,  1.0682,  1.0461, -0.0229, -0.0103],
        [ 0.1144,  2.2331, -0.1329, -1.0320,  1.0635]])

In [39]:
t.shape

torch.Size([3, 4, 5])

In [48]:
l = [('a', 1), ('c', 3), ('b', 2)]

In [53]:
sorted(l, key=lambda x: x[1], reverse=True)[:3]

[('c', 3), ('b', 2), ('a', 1)]

In [56]:
print("{0:.2f}, {1:.2f}".format(3.678, 8.678))

3.68, 8.68


## Create word vocab

In [25]:
data_dir = '/nfs/team/nlp/users/rgupta/NMT/code/GNN-Semantic-Similarity/data/'
langs = ['en', 'de']

In [ ]:
word_sents = []
with open(join(data_dir, ))

In [11]:
t.shape

torch.Size([10, 5, 12])

In [18]:
t[1]

tensor([[3, 5, 6, 9, 2, 0, 9, 3, 2, 8, 3, 8],
        [9, 9, 4, 4, 1, 2, 1, 2, 0, 3, 1, 5],
        [3, 1, 7, 3, 9, 9, 6, 3, 4, 6, 9, 3],
        [4, 6, 8, 1, 4, 1, 8, 6, 4, 5, 5, 0],
        [6, 1, 3, 0, 6, 7, 8, 6, 4, 5, 9, 6]])

In [19]:
l = list(range(10))

In [23]:
l[:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [20]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
t[:, -1, :]

tensor([[5, 5, 9, 9, 2, 4, 6, 9, 4, 7, 2, 6],
        [6, 1, 3, 0, 6, 7, 8, 6, 4, 5, 9, 6],
        [2, 9, 9, 2, 1, 1, 4, 4, 1, 0, 7, 5],
        [0, 6, 6, 1, 7, 9, 1, 7, 7, 3, 1, 3],
        [1, 2, 4, 2, 0, 1, 0, 4, 9, 3, 8, 5],
        [5, 1, 4, 8, 0, 9, 5, 4, 4, 3, 6, 9],
        [5, 6, 0, 4, 8, 0, 0, 1, 3, 1, 2, 9],
        [9, 5, 5, 2, 4, 4, 6, 0, 4, 3, 7, 2],
        [4, 7, 1, 0, 6, 4, 2, 1, 0, 8, 3, 9],
        [5, 2, 0, 2, 5, 2, 5, 3, 6, 6, 1, 4]])

In [8]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
torch.cat((torch.ones(5), torch.zeros(5)))

tensor([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [ ]:
torch.cat((torch.arange(a
                       )))

In [8]:
vocab_sizes = [500, 50000]

In [13]:
with open('../data/processed/tokens_dataset.pickle', 'rb') as f:
    data = pickle.load(f)

In [51]:
def create_consec_dict(d):
    res = {'UNK': 0}
    for k, v in d.items():
        res[k] = len(res)
    return res

In [52]:
vocabs = {}
for v in vocab_sizes:
    with open(f'../data/vocabs/iwslt14-en-de-{v}-vocab.txt', 'r') as f:
        vocabs[v] = create_consec_dict(dict([line.strip().split() for line in f]))

In [53]:
data['en'][500][:5]

[[['▁It'],
  ['▁can'],
  ['▁be'],
  ['▁a'],
  ['▁very'],
  ['▁com', 'p', 'l', 'ic', 'at', 'ed'],
  ['▁thing', ','],
  ['▁the'],
  ['▁o', 'ce', 'an', '.']],
 [['▁And'],
  ['▁it'],
  ['▁can'],
  ['▁be'],
  ['▁a'],
  ['▁very'],
  ['▁com', 'p', 'l', 'ic', 'at', 'ed'],
  ['▁thing', ','],
  ['▁what'],
  ['▁h', 'um', 'an'],
  ['▁he', 'al', 'th'],
  ['▁is', '.']],
 [['▁And'],
  ['▁b', 'r', 'ing', 'ing'],
  ['▁th', 'o', 'se'],
  ['▁t', 'w', 'o'],
  ['▁to', 'g', 'et', 'her'],
  ['▁m', 'ight'],
  ['▁se', 'em'],
  ['▁a'],
  ['▁very'],
  ['▁da', 'un', 't', 'ing'],
  ['▁t', 'as', 'k', ','],
  ['▁but'],
  ['▁what'],
  ['▁I', "'", 'm'],
  ['▁going'],
  ['▁to'],
  ['▁tr', 'y'],
  ['▁to'],
  ['▁s', 'ay'],
  ['▁is'],
  ['▁that'],
  ['▁e', 'v', 'en'],
  ['▁in'],
  ['▁that'],
  ['▁com', 'p', 'le', 'x', 'ity', ','],
  ['▁there', "'", 's'],
  ['▁som', 'e'],
  ['▁s', 'im', 'p', 'le'],
  ['▁them', 'es'],
  ['▁that'],
  ['▁I'],
  ['▁think', ','],
  ['▁if'],
  ['▁we'],
  ['▁und', 'er', 'st', 'and', ','],
  ['▁we

In [54]:
vocabs[500]

{'UNK': 0,
 ',': 1,
 '.': 2,
 's': 3,
 'en': 4,
 't': 5,
 'e': 6,
 'er': 7,
 '▁the': 8,
 'a': 9,
 'r': 10,
 'o': 11,
 'n': 12,
 '▁in': 13,
 '▁a': 14,
 'l': 15,
 'h': 16,
 'm': 17,
 'es': 18,
 'f': 19,
 'y': 20,
 'p': 21,
 'g': 22,
 'd': 23,
 're': 24,
 'ing': 25,
 'u': 26,
 'i': 27,
 'it': 28,
 '▁to': 29,
 '▁w': 30,
 'b': 31,
 "'": 32,
 '▁s': 33,
 'al': 34,
 'k': 35,
 '▁d': 36,
 'ar': 37,
 '▁of': 38,
 'te': 39,
 'le': 40,
 '▁b': 41,
 'at': 42,
 'in': 43,
 'an': 44,
 '▁and': 45,
 '▁g': 46,
 '▁die': 47,
 'c': 48,
 '▁I': 49,
 'ch': 50,
 'w': 51,
 '▁f': 52,
 '▁m': 53,
 'ed': 54,
 '▁h': 55,
 'is': 56,
 '▁und': 57,
 '▁p': 58,
 'ä': 59,
 '▁l': 60,
 '▁': 61,
 'ten': 62,
 'ie': 63,
 'on': 64,
 'z': 65,
 '▁c': 66,
 '▁M': 67,
 '▁that': 68,
 '▁be': 69,
 'or': 70,
 'ur': 71,
 '▁we': 72,
 'el': 73,
 'st': 74,
 'ra': 75,
 '▁you': 76,
 '▁t': 77,
 '▁der': 78,
 'et': 79,
 '▁ein': 80,
 'v': 81,
 'as': 82,
 '▁e': 83,
 'ent': 84,
 '▁W': 85,
 'll': 86,
 'ter': 87,
 'ig': 88,
 '▁n': 89,
 '▁wir': 90,
 '▁is': 

In [29]:
bilstm = BILSTM(128, 256, len(vocabs[500]))

In [37]:
data_flat = {lang: [[token for word in sent for token in word] for sent in data_vs[500]] for lang, data_vs in data.items()}

In [66]:
def collate_tokens(values):
    size = max(len(v) for v in values)
    res = np.zeros((len(values), size), dtype=np.long)
    
    for i, v in enumerate(values):
        res[i][:len(v)] = v

    return res

In [67]:
collate_tokens([[1,2,3],[1,2]])

array([[1, 2, 3],
       [1, 2, 0]])

In [55]:
l = len(data_flat['en'])

In [56]:
BATCH_SIZE = 32

In [68]:
batches = []

for i, batch_start in enumerate(range(0,l,BATCH_SIZE)):
    en = data_flat['en'][batch_start: batch_start + BATCH_SIZE]
    de = data_flat['de'][batch_start: batch_start + BATCH_SIZE]
    en = collate_tokens([[vocabs[500].get(token, 0) for token in sent] for sent in en])
    de = collate_tokens([[vocabs[500].get(token, 0) for token in sent] for sent in de])

In [73]:
bilstm(torch.tensor(en))

tensor([[[-4.2178e-03, -2.2162e-03,  8.8887e-03,  ..., -5.6052e-03,
          -5.9517e-02,  4.3833e-02],
         [ 1.2576e-02,  9.2151e-03, -2.9298e-02,  ..., -1.0797e-02,
          -7.3682e-02,  2.1178e-02],
         [-3.2531e-02, -4.2487e-04, -6.9737e-03,  ...,  2.2516e-04,
          -9.3891e-02,  1.6651e-02],
         ...,
         [ 5.9313e-02, -6.6641e-02,  1.5658e-01,  ..., -6.2147e-02,
          -3.3358e-02,  5.0430e-02],
         [ 8.9931e-03, -6.8983e-02,  1.2450e-01,  ..., -2.4962e-02,
          -7.0752e-02,  4.5551e-02],
         [ 2.3369e-02, -6.6386e-02,  7.4812e-02,  ..., -1.0721e-03,
          -6.1242e-02,  3.1662e-02]],

        [[-1.0074e-02,  1.7195e-02,  6.1169e-03,  ...,  4.0959e-02,
          -7.0635e-03,  1.0011e-02],
         [ 1.0934e-02,  4.3922e-02,  1.8624e-02,  ...,  5.1706e-02,
          -1.6128e-02,  1.1667e-02],
         [-8.2074e-03,  1.3459e-02,  3.6670e-02,  ...,  4.2992e-02,
           9.2687e-03,  5.8783e-02],
         ...,
         [ 7.5604e-02, -8

In [69]:
en

array([[ 49, 418, 415, ...,   0,   0,   0],
       [136, 114, 154, ...,   0,   0,   0],
       [181, 474, 174, ...,   0,   0,   0],
       ...,
       [236, 427,  76, ...,   0,   0,   0],
       [181, 135,  37, ...,   0,   0,   0],
       [181, 135,  37, ..., 172,   3,   2]])

In [26]:
s = torch.randn(10)

In [27]:
s

tensor([-0.9295,  1.4196, -0.5438, -1.3986,  1.0015, -0.4257,  0.4278, -1.1540,
        -0.2786,  1.5857])

In [32]:
(s < 1.) & (s > 0.)

tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=torch.uint8)

In [33]:
s

tensor([-0.9295,  1.4196, -0.5438, -1.3986,  1.0015, -0.4257,  0.4278, -1.1540,
        -0.2786,  1.5857])

In [36]:
assert 1 == 0, raise RunTimeError

SyntaxError: invalid syntax (<ipython-input-36-5a834387fb7d>, line 1)

In [48]:
tokens_500 = set()
for sent in data_flat['en']:
    for token in sent:
        tokens_500.add(token)